version: "3.9"

services:
  # PostgreSQL базы данных
  rights-postgres:
    image: postgres:16-alpine
    container_name: rights-postgres
    restart: always
    environment:
      POSTGRES_USER: ${RIGHTS_DB_USER}
      POSTGRES_PASSWORD: ${RIGHTS_DB_PASSWORD}
      POSTGRES_DB: rights-db
    ports:
      - "5435:5432"
    volumes:
      - rights_data:/var/lib/postgresql/data
    networks:
      - tablehub-network

  # Go-приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tablehub-app
    depends_on:
      - rights-postgres
    environment:
      CONFIG_PATH: /config.yaml
      RIGHTS_DB_USER: ${RIGHTS_DB_USER}
      RIGHTS_DB_PASSWORD: ${RIGHTS_DB_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - tablehub-network

  # Liquibase миграции
  rights-liquibase:
    image: liquibase/liquibase:latest
    container_name: rights-liquibase
    depends_on:
      - rights-postgres
    working_dir: /db
    command: >
      --classpath=drivers/postgresql-42.6.0.jar
      --url=jdbc:postgresql://rights-postgres:5432/rights-db
      --username=${RIGHTS_DB_USER}
      --password=${RIGHTS_DB_PASSWORD}
      --changeLogFile=./rights/changelog.yaml
      update
    volumes:
      - ./db/rights:/db/rights:ro
      - ./db/drivers:/db/drivers:ro
    networks:
      - tablehub-network


networks:
  tablehub-network:
    driver: bridge

volumes:
  rights_data:
